
[general]
import = [ "os.toml" ]

[font]
normal = { family = "RecMonoLinear Nerd Font Mono" }

[window]
opacity = 0.8
padding = { x = 5, y = 10 }
decorations = "None"

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true

[colors.primary]
foreground = "#dddddd"
background = "#000000"

[colors.normal]
black = "#000000"
white = "#cccccc"
red = "#ff8888"
green = "#88dd88"
yellow = "#eeee66"
blue = "#9a9aff"
magenta = "#ffaaff"
cyan = "#88cccc"

[colors.bright]
black = "#444444"
white = "#ffffff"
red = "#ffbbbb"
green = "#baddba"
yellow = "#ffffaa"
blue = "#bbbbff"
magenta = "#ffccff"
cyan = "#bbeeee"

